# Generated by Django 5.1.7 on 2025-03-26 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_tracking_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tracking_number',
        ),
    ]
